import { useEffect, useState, type FormEvent } from "react";

type Client={id:string;name:string;trade_name?:string;kind:"recurring"|"one_off"};
type Asset={id:string;client_id:string;title:string;kind:"video"|"photo";source:string;published_url?:string;created_at:string};
const url=(import.meta.env.VITE_SUPABASE_URL as string|undefined)||"https://xmjwdflvcusooinovgrg.supabase.co";
const key=(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined)||"sb_publishable_3WQ418LpynVy6Olq5zWJ7w_ehTHoF9l";
const headers=(token:string,extra:Record<string,string>={})=>({apikey:key,Authorization:`Bearer ${token}`,...extra});

export default function PortalAdmin({accessToken}:{accessToken:string}){
  const [clients,setClients]=useState<Client[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [error,setError]=useState("");const [open,setOpen]=useState(false);
  async function load(){try{const [c,m]=await Promise.all([fetch(`${url}/rest/v1/clients?select=id,name,trade_name,kind&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${url}/rest/v1/media_assets?select=id,client_id,title,kind,source,published_url,created_at&order=created_at.desc`,{headers:headers(accessToken)})]);if(!c.ok||!m.ok){const failed=!c.ok?c:m;const detail=await failed.json().catch(()=>null) as {message?:string}|null;throw new Error(detail?.message||`Não foi possível carregar o conteúdo (${failed.status}).`)}setClients(await c.json());setAssets(await m.json());setError("")}catch(reason){setError(reason instanceof TypeError?"A conexão com o banco falhou. Atualize a página para renovar sua sessão.":reason instanceof Error?reason.message:"Falha ao carregar o portal.")}}
  useEffect(()=>{void load()},[accessToken]);
  return <section className="portal-admin"><header className="dashboard-topbar"><div><p className="dashboard-kicker">Portal do cliente</p><h1>Conteúdo</h1><p>Publique vídeos, fotos e resultados com controle de acesso.</p></div><div className="dashboard-topbar-actions"><a className="dashboard-button secondary" href="/clientes" target="_blank">Abrir portal</a><button className="dashboard-button primary" onClick={()=>setOpen(true)}><span className="plus">+</span> Novo conteúdo</button></div></header>
    <div className="dashboard-stats"><article><span>Clientes no portal</span><strong>{String(clients.length).padStart(2,"0")}</strong><small>Com acesso individual</small></article><article><span>Vídeos</span><strong>{String(assets.filter(x=>x.kind==="video").length).padStart(2,"0")}</strong><small>Links e arquivos</small></article><article><span>Fotos</span><strong>{String(assets.filter(x=>x.kind==="photo").length).padStart(2,"0")}</strong><small>Itens de galeria</small></article><article><span>Compartilhamentos</span><strong>—</strong><small>Links públicos ativos</small></article></div>
    {error?<div className="portal-admin-setup"><span>Não foi possível carregar</span><h2>Falha de conexão</h2><p>{error}</p><button className="dashboard-button primary" onClick={()=>void load()}>Tentar novamente</button></div>:<section className="clients-card"><div className="clients-toolbar"><div><h2>Biblioteca</h2><span>{assets.length} conteúdos</span></div></div>{assets.length?<div className="portal-admin-grid">{assets.map(asset=><article key={asset.id}><div><span>{asset.kind}</span><small>{asset.source}</small></div><h3>{asset.title}</h3><p>{clients.find(c=>c.id===asset.client_id)?.trade_name||clients.find(c=>c.id===asset.client_id)?.name||"Cliente"}</p><a href={asset.published_url} target="_blank" rel="noreferrer">Visualizar ↗</a></article>)}</div>:<div className="clients-empty"><span>✦</span><h3>Biblioteca vazia</h3><p>Adicione o primeiro vídeo ou conjunto de fotos.</p><button className="dashboard-button primary" onClick={()=>setOpen(true)}>Novo conteúdo</button></div>}</section>}
    {open&&<MediaModal token={accessToken} clients={clients} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);void load()}}/>}
  </section>
}

function MediaModal({token,clients,onClose,onSaved}:{token:string;clients:Client[];onClose:()=>void;onSaved:()=>void}){
  const [clientId,setClientId]=useState(clients[0]?.id||"");const [kind,setKind]=useState<"video"|"photo">("video");const [title,setTitle]=useState("");const [source,setSource]=useState("instagram");const [publishedUrl,setPublishedUrl]=useState("");const [download,setDownload]=useState(false);const [views,setViews]=useState("");const [reach,setReach]=useState("");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch(`${url}/rest/v1/media_assets`,{method:"POST",headers:headers(token,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({client_id:clientId,kind,source,title,published_url:publishedUrl,allow_download:download})});const data=await response.json();if(!response.ok)throw new Error(data.message||"Não foi possível publicar.");if(kind==="video"&&(views||reach))await fetch(`${url}/rest/v1/media_metrics`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({media_id:data[0].id,views:Number(views)||0,reach:Number(reach)||0})});onSaved()}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao salvar.")}finally{setSaving(false)}}
  return <div className="client-modal-backdrop"><section className="client-modal"><header className="client-modal-header"><div><p className="dashboard-kicker">Biblioteca</p><h2>Novo conteúdo</h2><p>Associe o material ao cliente correto.</p></div><button className="modal-close" onClick={onClose}>×</button></header><form className="client-form" onSubmit={submit}><label className="dashboard-field full"><span>Cliente</span><select value={clientId} onChange={e=>setClientId(e.target.value)} required><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.name}</option>)}</select></label><div className="client-kind-picker full"><button type="button" className={kind==="video"?"active":""} onClick={()=>setKind("video")}><strong>Vídeo</strong><span>Instagram, YouTube ou arquivo</span></button><button type="button" className={kind==="photo"?"active":""} onClick={()=>setKind("photo")}><strong>Foto</strong><span>Imagem individual ou galeria</span></button></div><label className="dashboard-field full"><span>Título</span><input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="dashboard-field"><span>Origem</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="instagram">Instagram</option><option value="youtube">YouTube</option><option value="external">Link externo</option><option value="upload">Arquivo</option></select></label><label className="dashboard-field"><span>Link publicado</span><input type="url" value={publishedUrl} onChange={e=>setPublishedUrl(e.target.value)} required/></label>{kind==="video"&&<><label className="dashboard-field"><span>Visualizações</span><input type="number" min="0" value={views} onChange={e=>setViews(e.target.value)}/></label><label className="dashboard-field"><span>Alcance</span><input type="number" min="0" value={reach} onChange={e=>setReach(e.target.value)}/></label></>}<label className="finance-check full"><input type="checkbox" checked={download} onChange={e=>setDownload(e.target.checked)}/><span>Permitir download quando houver arquivo original</span></label>{error&&<p className="admin-error full">{error}</p>}<div className="client-form-actions full"><button className="dashboard-button secondary" type="button" onClick={onClose}>Cancelar</button><button className="dashboard-button primary" disabled={saving}>{saving?"Publicando…":"Publicar"}</button></div></form></section></div>
}
